### ISSUE TITLE
Created GitHub Page to Play

### ISSUE THREAD

**Issue by el3ctro-** [UstymUkhman/web-doom#2]
Steps to reproduce:
1.  I ran python -m http.server
2. Could play DOOM w/ keyboard & mouse on samsung smart tv w/ samsung web browser (Chromium I think),
3. Created GitHub Pages fork
4. Site is online at https://el3ctro-.github.io/webDOOM/public/
5.I actually had some trouble compiling on Termux, it says I don't have openGL installed which is sorta not true cause i can "make install"  SDL just fine with the right 'configure'.

Cheers
el3ctro-

**Comment by UstymUkhman** [comment]
Hi el3ctro-!
Awesome, thanks for forking this repo and testing it on Samsung Smart TV. Good to know DOOM can run even there. 😃 

Don't know much about compiling it on Termux, but what exactly gives you that error? Is it `build.sh`? If so, I assume there could be some issues, maybe related to [this line](https://github.com/UstymUkhman/webDOOM/blob/master/build.sh#L36). It's actually a hack for `emscripten` compiler. 😄 Maybe try to remove it and recompile again (the compiler will then use modern OpenGL libraries).

Let me know if you'll be successful in that.
Cheers!

**Comment by CataphractAoE** [comment]
Hello, how can I play this final doom/ultimate doom? How do I install that? I read the install file but it didn't make too much sense to me. Thanks!

**Comment by UstymUkhman** [comment]
Hi @CataphractAoE and welcome to GitHub!

I'm not quite sure that Final and Ultimate DOOM share the same codebase. I would assume so, but I haven't found any confirmation of that on respective wiki pages ([Final](https://en.wikipedia.org/wiki/Final_Doom) & [Ultimate](https://doom.fandom.com/wiki/The_Ultimate_Doom)).

One common thing they seem to share are updates in level design, so I would also assume it should be enough to replace [prboom.wad](https://github.com/UstymUkhman/webDOOM/blob/master/data/prboom.wad) file with one of those games and try to compile as usual.

Not sure, but that might work.
Good luck!

**Comment by CataphractAoE** [comment]
When you say "replace," you mean just by inserting the IWAD right? Also thank you very much for replying so quickly!

**Comment by UstymUkhman** [comment]
Sorry, it's been a while since I've worked on this, so got a little confused. Forget what I've said about `prboom.wad`. What you should do is to place your `.wad` file [here](https://github.com/UstymUkhman/webDOOM/tree/master/build) and rename it to `doom1.wad` before running `./build.sh` 'cause as you can see [here](https://github.com/UstymUkhman/webDOOM/blob/master/build.sh#L32), the script will search for this hardcoded file name.

**Comment by CataphractAoE** [comment]
Ah I see, I did that for TNT.WAD (A IWAD for final doom.) But how do I launch the game? The build.bat doesn't do anything as when I open it, it instantly closes itself after the cmd prompt pops up for 0.1 second XD Sorry for these stupid questions, and thank you replying back so quickly after 3 years! I also tried the Index.html file, selected Doom 1, but it just gets stuck on the loading screen with 0.0% :(((

**Comment by UstymUkhman** [comment]
Well, if you want to update WAD files, you have to rebuild it from scratch. You have to install a virtual machine with a 32-bit based OS, [PrBoom packages](http://prboom.sourceforge.net/linux.html) and an `emscripten` compiler. It's not a trivial task, but I've tried to describe it at my best [here](https://github.com/UstymUkhman/webDOOM#building-webdoom-on-debian).

**Comment by CataphractAoE** [comment]
Oh wow! I got it to work! Thank you very much! Just a side question, do you know how to convert WADs to JSON files?

**Comment by UstymUkhman** [comment]
Hi @CataphractAoE , I'm glad it worked! You're welcome. Please consider ⭐ing this project if you liked it. 😄 
I don't know much about this type of conversion, [this](https://github.com/nicokruger/py-wad2json) is the only util I was able to find. I guess it might help.
