### ISSUE TITLE
add pointer locking, its janky as hell LOL

### ISSUE THREAD

**Issue by PSYclownYT** [UstymUkhman/web-doom#3]

**Comment by UstymUkhman** [comment]
Hi @PSYclownYT! What browser are you using? This works pretty well for me on Chrome, but you need to enter the fullscreen mode (through) the button so it automatically will lock your pointer. Same on Firefox, but for whatever reason "WASD" keys are not working there, so you have to move by pressing your mouse right key.

**Comment by PSYclownYT** [comment]
chrome
chromeOS stable-build - grunt
managed device
