### ISSUE TITLE
full screen sucks 

### ISSUE THREAD

**Issue by ghost** [UstymUkhman/web-doom#4]
when i do full screen it won't work and my courser won't go away fix please

**Comment by UstymUkhman** [comment]
Do you use F11 or the button? What browser?
Related issue: https://github.com/UstymUkhman/webDOOM/issues/3 ?

**Comment by ghost** [comment]
i use Chromebook and google chrome

**Comment by UstymUkhman** [comment]
Can you send me a video with screen recording, plz?
