### ISSUE TITLE
Mouse issue

### ISSUE THREAD

**Issue by CoderGuyTedd** [UstymUkhman/web-doom#5]
The mouse isnt locked so you cant turn around

**Comment by UstymUkhman** [comment]
Hi @CoderGuyTedd! Can you share some details on the browser and the platmorm you're using? Also, it's not loked by default, have clicked the "Fullscreen" button when playing?

**Comment by CoderGuyTedd** [comment]
Its better to be locked by default but It works in fullscreen

**Comment by UstymUkhman** [comment]
I'm afraid it's not possible due to how PointerLock APIs work.

> Note: If a user has exited pointer lock via the [default unlock gesture](https://w3c.github.io/pointerlock/#dfn-default-unlock-gesture), or pointer lock has not previously been entered for this document, an event generated as a result of an [engagement gesture](https://w3c.github.io/pointerlock/#dfn-engagement-gesture) must be received by the document before [requestPointerLock](https://w3c.github.io/pointerlock/#dom-element-requestpointerlock) will succeed. (from https://w3c.github.io/pointerlock/#extensions-to-the-element-interface)

More info here: https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API#requestpointerlock
